<style type="text/css" media="screen, print">
    @page
    {
        size: auto;
        margin: 0px;
    }
    
    .card {
        width: 450px; height: 1200px; font-size: 12px;
        margin: 25px 15px 25px 40px;
    }
    
    .cert {
        width: 450px; height: 200px; font-size: 12px;
    }
    
    .rotate {
        -webkit-transform: rotate(90deg);
        -moz-transform: rotate(90deg);
        -o-transform: rotate(90deg);
        -ms-transform: rotate(90deg);
        transform: rotate(90deg);
        position: absolute; top: 1005px; left: -60px;
        overflow: hidden;
    }
    
    .rotate-ccw {
        -webkit-transform: rotate(-90deg);
        -moz-transform: rotate(-90deg);
        -o-transform: rotate(-90deg);
        -ms-transform: rotate(-90deg);
        transform: rotate(-90deg);
        position: absolute; top: 170px; left: 225px;
        overflow: hidden;
    }
</style>
<?php 
$data = $this->data[0];

$date = new \DateTime($data['DOB'],new \DateTimeZone('EDT'));
$DOB = $date->format('F d, Y');

$date = new \DateTime($data['DOR'],new \DateTimeZone('EDT'));
$DOR = $date->format('m/d/Y');

$date = new \DateTime($data['DOI'],new \DateTimeZone('EDT'));
$DOI = $date->format('m/d/Y');

?>
<!-- <div class="container border border-danger"> -->
<!-- 	<div class="row border border-primary"> -->
		<div class="rotate-ccw cert">
			<div class="row">
				<div class="col-2"></div>
				<div class="col-6 text-right">Registration No.:</div>
				<div class="col-4 border-bottom border-dark"><?php echo $data['SFN'];?></div>
    		</div>
    		<div class="row">
    			<div class="col-1"></div>
    			<div class="col-3">Name:</div>
    			<div class="col-8 border-bottom border-dark"><?php echo strtoupper($data['NAME']);?></div>
    		</div>
    		<div class="row">
    			<div class="col-1"></div>
    			<div class="col-3">Date of Birth:</div>
    			<div class="col-4 border-bottom border-dark"><?php echo strtoupper($DOB);?></div>
    			<div class="col-2">Sex:</div>
    			<div class="col-2 border-bottom border-dark"><?php echo strtoupper($data['SEX']);?></div>
    		</div>
    		<div class="row">
    			<div class="col-1"></div>
    			<div class="col-3">Place of Birth:</div>
    			<div class="col-8 border-bottom border-dark">MIDDLETOWN, CT</div>
    		</div>
    		<div class="row">
    			<div class="col-1"></div>
    			<div class="col-3">Reg. Date:</div>
    			<div class="col-2 border-bottom border-dark"><?php echo $DOR;?></div>
    			<div class="col-3 text-right">Date Issued:</div>
    			<div class="col-3 border-bottom border-dark"><?php echo $DOI;?></div>
    		</div>
    		<!-- <div class="row">
    			<div class="col-1"></div>
    			<div class="col-3">Date Issued:</div>
    			<div class="col-8 border-bottom border-dark"><?php echo $DOI;?></div>
    		</div>-->
    		<div class="row">
    			<div class="col-1"></div>
    			<div class="col-3">Place Issued:</div>
    			<div class="col-8 border-bottom border-dark">MIDDLETOWN, CT</div>
    		</div>
		</div>
<script type="text/javascript">
	window.print();
</script>
<!-- 	</div> -->
<!-- </div> -->